### ISSUE TITLE
Order flag suppressed in review when slash is selected

### ISSUE THREAD

**Issue by jshapiro651** [ConOnRails/ConOnRails#44]
In the Review tab, there are three buttons associated with each flag (Active, Emergency, Allocations, etc.).  These buttons read, from left to right, as a check mark (to select for that flag), a slash (to select against that flag), and an X (to ignore that flag).

The final flag is labeled "Order," followed by an Up Arrow (oldest first) and a Down Arrow (most recent first) button.

Selecting the slash button for any flag appears to suppress the function of the “Order” flag, forcing it to act as if it is in the “up arrow” position, regardless of which button is actually selected.

**Comment by mshappe** [comment]
It appears that selecting any "slash" suppresses all other flags after it (including order). You can see this most visibly if you select the slash for "active"!

**Comment by mshappe** [comment]
The bug is a misunderstanding on my part of the jQuery `.each()` method, which assumes that a `false` value means "break the loop". If a flag inside the loop gets set false...the loop breaks! Working around it should not be hard, since we never actually want the loop to break, and can therefore explicitly return true.

**Comment by mshappe** [comment]
(also, this would not have been a problem in actual JavaScript, but the code in question is CoffeeScript, which among other things adopts Ruby's semantics of returning the last value seen in the absence of any explicit return instruction)
